-- CHECK-SCHEMA: TABLE
-- CHECK-SCHEMA:   NAME foo
-- CHECK-SCHEMA:   COLUMNS
-- CHECK-SCHEMA:       KEY bar
-- CHECK-SCHEMA:       VALUE TEXT?
-- CHECK-SCHEMA:       KEY quz
-- CHECK-SCHEMA:       VALUE INTEGER
-- CHECK-SCHEMA:   KIND fts5
-- CHECK-ERROR: Missing column type
CREATE VIRTUAL TABLE foo USING fts5 (
    bar TEXT,
    baz UNINDEXED,
    quz INTEGER NOT NULL
);

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   OUTPUT
-- CHECK-QUERIES:     bar TEXT?
-- CHECK-QUERIES:     quz INTEGER
SELECT * FROM foo;

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   OUTPUT
-- CHECK-QUERIES:     bar TEXT?
-- CHECK-QUERIES:     quz INTEGER
SELECT * FROM foo ORDER BY rank ASC;

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   OUTPUT
-- CHECK-QUERIES:     bar TEXT?
-- CHECK-QUERIES:     quz INTEGER
SELECT * FROM foo WHERE foo MATCH 'search terms' ORDER BY rank;

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   PARAMETERS
-- CHECK-QUERIES:     PARAMETER
-- CHECK-QUERIES:       TYPE TEXT
-- CHECK-QUERIES:       INDEX 1
-- CHECK-QUERIES:       NAME :terms
-- CHECK-QUERIES:   OUTPUT
-- CHECK-QUERIES:     bar TEXT?
SELECT bar FROM foo WHERE foo MATCH :terms;
