CREATE TABLE foo (bar INTEGER, baz INTEGER);

-- CHECK: SIGNATURE
DELETE FROM foo;

-- CHECK: SIGNATURE
-- CHECK:   PARAMETERS
-- CHECK:     PARAMETER
-- CHECK:       TYPE INTEGER?
-- CHECK:       INDEX 1
-- CHECK:       NAME bar
DELETE FROM foo WHERE bar = ?;

-- CHECK: SIGNATURE
-- CHECK:   OUTPUT
-- CHECK:     bar INTEGER?
-- CHECK:     baz INTEGER?
DELETE FROM foo RETURNING *;
