CREATE TABLE foo (id INTEGER PRIMARY KEY, bar INTEGER, baz TEXT NOT NULL);

-- CHECK: COMPILED_QUERY
-- CHECK:   PARAMETERS
-- CHECK:     PARAMETER
-- CHECK:       TYPE INTEGER
-- CHECK:       INDEX 1
-- CHECK:       NAME
-- CHECK:   OUTPUT
-- CHECK:     id INTEGER
-- CHECK:     bar INTEGER?
-- CHECK:     baz TEXT
SELECT * FROM foo WHERE id = ?;

-- CHECK: COMPILED_QUERY
-- CHECK:   PARAMETERS
-- CHECK:     PARAMETER
-- CHECK:       TYPE INTEGER?
-- CHECK:       INDEX 1
-- CHECK:       NAME
-- CHECK:   OUTPUT
-- CHECK:     id INTEGER
-- CHECK:     bar INTEGER?
SELECT id, bar + 1 FROM foo WHERE bar * 20 > ?;
