//
//  Token.swift
//  
//
//  Created by Wes Wickwire on 10/8/24.
//

struct Token {
    let kind: Kind
    let range: Range<String.Index>
    
    static let keywords: [String: Kind] = [
        "ABORT": .abort,
        "ACTION": .action,
        "ADD": .add,
        "AFTER": .after,
        "ALL": .all,
        "ALTER": .alter,
        "ALWAYS": .always,
        "ANALYZE": .analyze,
        "AND": .and,
        "AS": .as,
        "ASC": .asc,
        "ATTACH": .attach,
        "AUTOINCREMENT": .autoincrement,
        "BEFORE": .before,
        "BEGIN": .begin,
        "BETWEEN": .between,
        "BY": .by,
        "CASCADE": .cascade,
        "CASE": .case,
        "CAST": .cast,
        "CHECK": .check,
        "COLLATE": .collate,
        "COLUMN": .column,
        "COMMIT": .commit,
        "CONFLICT": .conflict,
        "CONSTRAINT": .constraint,
        "CREATE": .create,
        "CROSS": .cross,
        "CURRENT": .current,
        "CURRENT_DATE": .currentDate,
        "CURRENT_TIME": .currentTime,
        "CURRENT_TIMESTAMP": .currentTimestamp,
        "DATABASE": .database,
        "DEFAULT": .default,
        "DEFERRABLE": .deferrable,
        "DEFERRED": .deferred,
        "DELETE": .delete,
        "DESC": .desc,
        "DETACH": .detach,
        "DISTINCT": .distinct,
        "DO": .do,
        "DROP": .drop,
        "EACH": .each,
        "ELSE": .else,
        "END": .end,
        "ESCAPE": .escape,
        "EXCEPT": .except,
        "EXCLUDE": .exclude,
        "EXCLUSIVE": .exclusive,
        "EXISTS": .exists,
        "EXPLAIN": .explain,
        "FAIL": .fail,
        "FILTER": .filter,
        "FIRST": .first,
        "FOLLOWING": .following,
        "FOR": .for,
        "FOREIGN": .foreign,
        "FROM": .from,
        "FULL": .full,
        "GENERATED": .generated,
        "GLOB": .glob,
        "GROUP": .group,
        "GROUPS": .groups,
        "HAVING": .having,
        "IF": .if,
        "IGNORE": .ignore,
        "IMMEDIATE": .immediate,
        "IN": .in,
        "INDEX": .index,
        "INDEXED": .indexed,
        "INITIALLY": .initially,
        "INNER": .inner,
        "INSERT": .insert,
        "INSTEAD": .instead,
        "INTERSECT": .intersect,
        "INTO": .into,
        "IS": .is,
        "ISNULL": .isnull,
        "JOIN": .join,
        "KEY": .key,
        "LAST": .last,
        "LEFT": .left,
        "LIKE": .like,
        "LIMIT": .limit,
        "MATCH": .match,
        "MATERIALIZED": .materialized,
        "NATURAL": .natural,
        "NO": .no,
        "NOT": .not,
        "NOTHING": .nothing,
        "NOTNULL": .notnull,
        "NULL": .null,
        "NULLS": .nulls,
        "OF": .of,
        "OFFSET": .offset,
        "ON": .on,
        "OR": .or,
        "ORDER": .order,
        "OTHERS": .others,
        "OUTER": .outer,
        "OVER": .over,
        "PARTITION": .partition,
        "PLAN": .plan,
        "PRAGMA": .pragma,
        "PRECEDING": .preceding,
        "PRIMARY": .primary,
        "QUERY": .query,
        "RAISE": .raise,
        "RANGE": .range,
        "RECURSIVE": .recursive,
        "REFERENCES": .references,
        "REGEXP": .regexp,
        "REINDEX": .reindex,
        "RELEASE": .release,
        "RENAME": .rename,
        "REPLACE": .replace,
        "RESTRICT": .restrict,
        "RETURNING": .returning,
        "RIGHT": .right,
        "ROLLBACK": .rollback,
        "ROW": .row,
        "ROWS": .rows,
        "SAVEPOINT": .savepoint,
        "SELECT": .select,
        "SET": .set,
        "TABLE": .table,
        "TEMP": .temp,
        "TEMPORARY": .temporary,
        "THEN": .then,
        "TIES": .ties,
        "TO": .to,
        "TRANSACTION": .transaction,
        "TRIGGER": .trigger,
        "UNBOUNDED": .unbounded,
        "UNION": .union,
        "UNIQUE": .unique,
        "UPDATE": .update,
        "USING": .using,
        "VACUUM": .vacuum,
        "VALUES": .values,
        "VIEW": .view,
        "VIRTUAL": .virtual,
        "WHEN": .when,
        "WHERE": .where,
        "WINDOW": .window,
        "WITH": .with,
        "WITHOUT": .without,
    ]
    
    enum Kind: Equatable {
        case symbol(Substring)
        
        case abort
        case action
        case add
        case after
        case all
        case alter
        case always
        case analyze
        case and
        case `as`
        case asc
        case attach
        case autoincrement
        case before
        case begin
        case between
        case by
        case cascade
        case `case`
        case cast
        case check
        case collate
        case column
        case commit
        case conflict
        case constraint
        case create
        case cross
        case current
        case currentDate
        case currentTime
        case currentTimestamp
        case database
        case `default`
        case deferrable
        case deferred
        case delete
        case desc
        case detach
        case distinct
        case `do`
        case drop
        case each
        case `else`
        case end
        case escape
        case except
        case exclude
        case exclusive
        case exists
        case explain
        case fail
        case filter
        case first
        case following
        case `for`
        case foreign
        case from
        case full
        case generated
        case glob
        case group
        case groups
        case having
        case `if`
        case ignore
        case immediate
        case `in`
        case index
        case indexed
        case initially
        case inner
        case insert
        case instead
        case intersect
        case into
        case `is`
        case isnull
        case join
        case key
        case last
        case left
        case like
        case limit
        case match
        case materialized
        case natural
        case no
        case not
        case nothing
        case notnull
        case null
        case nulls
        case of
        case offset
        case on
        case or
        case order
        case others
        case outer
        case over
        case partition
        case plan
        case pragma
        case preceding
        case primary
        case query
        case raise
        case range
        case recursive
        case references
        case regexp
        case reindex
        case release
        case rename
        case replace
        case restrict
        case returning
        case right
        case rollback
        case row
        case rows
        case savepoint
        case select
        case set
        case table
        case temp
        case temporary
        case then
        case ties
        case to
        case transaction
        case trigger
        case unbounded
        case union
        case unique
        case update
        case using
        case vacuum
        case values
        case view
        case virtual
        case when
        case `where`
        case window
        case with
        case without
        
        // Operators
        case star
        case dot
        case comma
        case singleQuote
        case openParen
        case closeParen
        case plus
        case minus
        case divide
        case multiply
        case modulo
        case shiftLeft
        case shiftRight
        case bitwiseAnd
        case bitwiseOr
        case bitwiseXor
        case concat
        case tilde
        case doubleEqual
        case notEqual
        case arrow
        case doubleArrow
        
        // Comparisons
        case lt
        case lte
        case gt
        case gte
        
        // Comments
        case dashDash
        case forwardSlashStar
        case starForwardSlash
        
        case eof

        init(word: Substring) {
            // TODO: There has to be a more performant way of doing this.
            if let keyword = Token.keywords[word.uppercased()] {
                self = keyword
            } else {
                self = .symbol(word)
            }
        }
    }
}
