CREATE TABLE foo (bar INTEGER, baz INTEGER);

-- CHECK: SIGNATURE
-- CHECK:   TABLES
-- CHECK:     foo
DELETE FROM foo;

-- CHECK: SIGNATURE
-- CHECK:   PARAMETERS
-- CHECK:     PARAMETER
-- CHECK:       TYPE INTEGER?
-- CHECK:       INDEX 1
-- CHECK:       NAME bar
-- CHECK:   TABLES
-- CHECK:     foo
DELETE FROM foo WHERE bar = ?;

-- CHECK: SIGNATURE
-- CHECK:   OUTPUT_CHUNKS
-- CHECK:     CHUNK
-- CHECK:       OUTPUT
-- CHECK:         bar INTEGER?
-- CHECK:         baz INTEGER?
-- CHECK:   TABLES
-- CHECK:     foo
DELETE FROM foo RETURNING *;
