-- CHECK-SCHEMA: TABLE
-- CHECK-SCHEMA:   ...
CREATE TABLE foo (bar INTEGER, baz TEXT);

-- CHECK-SCHEMA: TABLE
-- CHECK-SCHEMA:   NAME main.view1
-- CHECK-SCHEMA:   COLUMNS
-- CHECK-SCHEMA:       KEY bar
-- CHECK-SCHEMA:       VALUE INTEGER?
-- CHECK-SCHEMA:       KEY baz
-- CHECK-SCHEMA:       VALUE TEXT?
-- CHECK-SCHEMA:   KIND view
CREATE VIEW view1 AS SELECT * FROM foo;

-- CHECK-SCHEMA: TABLE
-- CHECK-SCHEMA:   NAME main.view2
-- CHECK-SCHEMA:   COLUMNS
-- CHECK-SCHEMA:       KEY col1
-- CHECK-SCHEMA:       VALUE INTEGER?
-- CHECK-SCHEMA:       KEY col2
-- CHECK-SCHEMA:       VALUE TEXT?
-- CHECK-SCHEMA:   KIND view
CREATE VIEW view2 (col1, col2) AS SELECT * FROM foo;

-- CHECK-SCHEMA: TABLE
-- CHECK-SCHEMA:   NAME main.view3
-- CHECK-SCHEMA:   COLUMNS
-- CHECK-SCHEMA:       KEY col1
-- CHECK-SCHEMA:       VALUE INTEGER?
-- CHECK-SCHEMA:   KIND view
-- CHECK-ERROR: SELECT returns 2 columns but only have 1 names defined
CREATE VIEW view3 (col1) AS SELECT * FROM foo;

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   OUTPUT_CHUNKS
-- CHECK-QUERIES:     CHUNK
-- CHECK-QUERIES:       OUTPUT
-- CHECK-QUERIES:         bar INTEGER?
-- CHECK-QUERIES:         baz TEXT?
-- CHECK-QUERIES:       OUTPUT_TABLE view1
-- CHECK-QUERIES:   TABLES
-- CHECK-QUERIES:     view1
SELECT * FROM view1;

-- CHECK-QUERIES: SIGNATURE
-- CHECK-QUERIES:   OUTPUT_CHUNKS
-- CHECK-QUERIES:     CHUNK
-- CHECK-QUERIES:       OUTPUT
-- CHECK-QUERIES:         col1 INTEGER?
-- CHECK-QUERIES:         col2 TEXT?
-- CHECK-QUERIES:       OUTPUT_TABLE view2
-- CHECK-QUERIES:   TABLES
-- CHECK-QUERIES:     view2
SELECT * FROM view2;

CREATE VIEW willDrop AS SELECT * FROM foo;
DROP VIEW willDrop;
DROP VIEW IF EXISTS willDrop;

-- CHECK-ERROR: View with name does not exist
DROP VIEW dne;
