name: Release

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.destination.name }}
    runs-on: ${{ matrix.destination.os }}
    strategy:
      matrix:
        destination:
          # - Swiftly is failing to install these so commenting out for now
          # - { name: "ubuntu-aarch64", os: ubuntu-22.04-arm }
          # - { name: "ubuntu-x86_64", os: ubuntu-22.04 }
          - { name: "macos-universal", os: macos-15 }
    steps:
    - if: startsWith(matrix.destination.name, 'ubuntu')
      uses: vapor/swiftly-action@v0.2
      with:
        toolchain: 6.1.0
    - if: startsWith(matrix.destination.name, 'macos')
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - uses: actions/checkout@v4
    - name: Create the binary
      run: make release OUTPUT_NAME=puresql.${{ matrix.destination.name }}.tar.gz
    - name: Upload the binary
      uses: actions/upload-artifact@v4
      with:
        name: puresql.${{ matrix.destination.name }}.tar.gz
        path: puresql.${{ matrix.destination.name }}.tar.gz

  deploy-binary:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Deploy the binary
      uses: softprops/action-gh-release@v2
      with:
        files: puresql.macos-universal.tar.gz
          # puresql.ubuntu-x86_64.tar.gz
          # puresql.ubuntu-aarch64.tar.gz