-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     PRIMARY_KEY
-- CHECK:       ORDER asc
-- CHECK:       CONFICT_CLAUSE none
-- CHECK:       AUTOINCREMENT false
PRIMARY KEY

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     PRIMARY_KEY
-- CHECK:       ORDER desc
-- CHECK:       CONFICT_CLAUSE none
-- CHECK:       AUTOINCREMENT true
PRIMARY KEY DESC AUTOINCREMENT

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     PRIMARY_KEY
-- CHECK:       ORDER desc
-- CHECK:       CONFICT_CLAUSE fail
-- CHECK:       AUTOINCREMENT true
PRIMARY KEY DESC ON CONFLICT FAIL AUTOINCREMENT

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME toUser
-- CHECK:   KIND
-- CHECK:     FOREIGN_KEY
-- CHECK:       FOREIGN_TABLE user
-- CHECK:       FOREIGN_COLUMNS
-- CHECK:         id
-- CHECK:       ACTIONS
-- CHECK:         ACTION
-- CHECK:           ON_DO
-- CHECK:             ON delete
-- CHECK:             DO cascade
CONSTRAINT toUser REFERENCES user(id) ON DELETE CASCADE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     FOREIGN_KEY
-- CHECK:       FOREIGN_TABLE user
-- CHECK:       FOREIGN_COLUMNS
-- CHECK:         id
-- CHECK:       ACTIONS
-- CHECK:         ACTION
-- CHECK:           ON_DO
-- CHECK:             ON delete
-- CHECK:             DO cascade
REFERENCES user(id) ON DELETE CASCADE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME isNotNull
-- CHECK:   KIND
-- CHECK:     NOT_NULL none
CONSTRAINT isNotNull NOT NULL

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     NOT_NULL fail
NOT NULL ON CONFLICT FAIL

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     NOT_NULL none
NOT NULL

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME isUnique
-- CHECK:   KIND
-- CHECK:     UNIQUE none
CONSTRAINT isUnique UNIQUE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     UNIQUE rollback
UNIQUE ON CONFLICT rollback

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     UNIQUE none
UNIQUE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME checkSomething
-- CHECK:   KIND
-- CHECK:     CHECK
-- CHECK:       LITERAL 1.0
CONSTRAINT checkSomething CHECK(1)

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     CHECK
-- CHECK:       LITERAL 1.0
CHECK(1)

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME setDefault
-- CHECK:   KIND
-- CHECK:     DEFAULT
-- CHECK:       LITERAL 1.0
CONSTRAINT setDefault DEFAULT 1

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     DEFAULT
-- CHECK:       LITERAL 1.0
DEFAULT (1)

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME hasCollate
-- CHECK:   KIND
-- CHECK:     COLLATE SIMPLE
CONSTRAINT hasCollate COLLATE SIMPLE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   KIND
-- CHECK:     COLLATE SIMPLE
COLLATE SIMPLE

-- CHECK: COLUMN_CONSTRAINT
-- CHECK:   NAME generateTheColumn
-- CHECK:   KIND
-- CHECK:     GENERATED
-- CHECK:         LITERAL 1.0
-- CHECK:       virtual
CONSTRAINT generateTheColumn GENERATED ALWAYS AS (1) VIRTUAL
