-- CHECK: COLUMN_DEF
-- CHECK:   NAME age
-- CHECK:   TYPE
-- CHECK:     NAME INT
-- CHECK:     RESOLVED int
age INT;

-- CHECK: COLUMN_DEF
-- CHECK:   NAME age
-- CHECK:   TYPE
-- CHECK:     NAME BIGINT
age BIGINT;

-- CHECK: COLUMN_DEF
-- CHECK:   NAME age
-- CHECK:   TYPE
-- CHECK:     NAME UNSIGNED BIG INT
-- CHECK:   CONSTRAINTS
-- CHECK:     COLUMN_CONSTRAINT
-- CHECK:       KIND
-- CHECK:         NOT_NULL none
age UNSIGNED BIG INT NOT NULL
