-- CHECK: CONFICT_CLAUSE rollback
ON CONFLICT ROLLBACK
-- CHECK: CONFICT_CLAUSE abort
ON CONFLICT ABORT
-- CHECK: CONFICT_CLAUSE fail
ON CONFLICT FAIL
-- CHECK: CONFICT_CLAUSE ignore
ON CONFLICT IGNORE
-- CHECK: CONFICT_CLAUSE replace
ON CONFLICT REPLACE
