-- CHECK: CONFICT_CLAUSE_SYNTAX rollback
ON CONFLICT ROLLBACK
-- CHECK: CONFICT_CLAUSE_SYNTAX abort
ON CONFLICT ABORT
-- CHECK: CONFICT_CLAUSE_SYNTAX fail
ON CONFLICT FAIL
-- CHECK: CONFICT_CLAUSE_SYNTAX ignore
ON CONFLICT IGNORE
-- CHECK: CONFICT_CLAUSE_SYNTAX replace
ON CONFLICT REPLACE
