-- CHECK: JOIN_CONSTRAINT
-- CHECK:   ON
-- CHECK:     LITERAL 1.0
ON 1;

-- CHECK: JOIN_CONSTRAINT
-- CHECK:   USING
-- CHECK:     id
USING (id);

-- CHECK: JOIN_CONSTRAINT
-- CHECK:   USING
-- CHECK:     foo
-- CHECK:     bar
USING (foo, bar);
