-- CHECK: BEGIN_STMT_SYNTAX
BEGIN;
-- CHECK: BEGIN_STMT_SYNTAX

BEGIN TRANSACTION;
-- CHECK: BEGIN_STMT_SYNTAX
-- CHECK:   KIND deferred

BEGIN DEFERRED TRANSACTION;
-- CHECK: BEGIN_STMT_SYNTAX
-- CHECK:   KIND immediate
BEGIN IMMEDIATE TRANSACTION;

-- CHECK: BEGIN_STMT_SYNTAX
-- CHECK:   KIND exclusive
BEGIN EXCLUSIVE TRANSACTION;

-- CHECK: COMMIT_STMT_SYNTAX
COMMIT;

-- CHECK: COMMIT_STMT_SYNTAX
COMMIT TRANSACTION;

-- CHECK: COMMIT_STMT_SYNTAX
END;

-- CHECK: COMMIT_STMT_SYNTAX
END TRANSACTION;

-- CHECK: ROLLBACK_STMT_SYNTAX
ROLLBACK;

-- CHECK: ROLLBACK_STMT_SYNTAX
ROLLBACK TRANSACTION;

-- CHECK: ROLLBACK_STMT_SYNTAX
-- CHECK:   SAVEPOINT foo
ROLLBACK TO SAVEPOINT foo;
