-- CHECK: INSERT_STMT_SYNTAX
-- CHECK:   ACTION
-- CHECK:     KIND
-- CHECK:       INSERT
-- CHECK:   TABLE_NAME
-- CHECK:     NAME foo
-- CHECK:   COLUMNS
-- CHECK:     bar
-- CHECK:     baz
-- CHECK:   VALUES
-- CHECK:     SELECT
-- CHECK:       SELECTS
-- CHECK:         SINGLE
-- CHECK:           VALUES
-- CHECK:             EXPRESSION_SYNTAX
-- CHECK:               LITERAL 1.0
-- CHECK:             EXPRESSION_SYNTAX
-- CHECK:               LITERAL 'two'
INSERT INTO foo (bar, baz) VALUES (1, 'two');

-- CHECK: INSERT_STMT_SYNTAX
-- CHECK:   ACTION
-- CHECK:     KIND replace
-- CHECK:   TABLE_NAME
-- CHECK:     NAME foo
-- CHECK:   COLUMNS
-- CHECK:     bar
-- CHECK:   VALUES
-- CHECK:     SELECT
-- CHECK:       SELECTS
-- CHECK:         SINGLE
-- CHECK:           SELECT
-- CHECK:             DISTINCT false
-- CHECK:             COLUMNS
-- CHECK:               RESULT_COLUMN_SYNTAX
-- CHECK:                 KIND
-- CHECK:                   EXPR
-- CHECK:                       COLUMN
-- CHECK:                         COLUMN baz
-- CHECK:             FROM
-- CHECK:               JOIN
-- CHECK:                 TABLE_OR_SUBQUERY
-- CHECK:                   KIND
-- CHECK:                     TABLE
-- CHECK:                       NAME qux
-- CHECK:   RETURNING_CLAUSE
-- CHECK:     VALUES
-- CHECK:       VALUE
-- CHECK:         EXPR
-- CHECK:           EXPR
-- CHECK:             COLUMN
-- CHECK:               COLUMN bar
REPLACE INTO foo (bar) SELECT baz FROM qux RETURNING bar;

-- CHECK: INSERT_STMT_SYNTAX
-- CHECK:   WITH
-- CHECK:     RECURSIVE true
-- CHECK:     CTES
-- CHECK:       COMMON_TABLE_EXPRESSION_SYNTAX
-- CHECK:         TABLE foo
-- CHECK:         MATERIALIZED false
-- CHECK:         SELECT
-- CHECK:           SELECTS
-- CHECK:             SINGLE
-- CHECK:               SELECT
-- CHECK:                 DISTINCT false
-- CHECK:                 COLUMNS
-- CHECK:                   RESULT_COLUMN_SYNTAX
-- CHECK:                     KIND
-- CHECK:                       EXPR
-- CHECK:                           COLUMN
-- CHECK:                             COLUMN bar
-- CHECK:                 FROM
-- CHECK:                   JOIN
-- CHECK:                     TABLE_OR_SUBQUERY
-- CHECK:                       KIND
-- CHECK:                         TABLE
-- CHECK:                           NAME baz
-- CHECK:   ACTION
-- CHECK:     KIND
-- CHECK:       INSERT
-- CHECK:         KIND replace
-- CHECK:   TABLE_NAME
-- CHECK:     NAME user
WITH RECURSIVE foo AS (SELECT bar FROM baz)
INSERT OR REPLACE INTO user DEFAULT VALUES;
