-- CHECK: VACUUM_STMT_SYNTAX
VACUUM;

-- CHECK: VACUUM_STMT_SYNTAX
-- CHECK:   SCHEMA main
VACUUM main;

-- CHECK: VACUUM_STMT_SYNTAX
-- CHECK:   FILE_NAME foo
VACUUM INTO foo;

-- CHECK: VACUUM_STMT_SYNTAX
-- CHECK:   SCHEMA main
-- CHECK:   FILE_NAME foo
VACUUM main INTO foo;
