-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR 1.0
1;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR 1.0
-- CHECK:   ORDER asc
1 ASC;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR 1.0
-- CHECK:   ORDER desc
1 DESC;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR
-- CHECK:       LHS 1.0
-- CHECK:       OPERATOR COLLATE NOCASE
1 COLLATE NOCASE;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR
-- CHECK:       LHS 1.0
-- CHECK:       OPERATOR COLLATE NOCASE
-- CHECK:   ORDER asc
1 COLLATE NOCASE ASC;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR
-- CHECK:       LHS 1.0
-- CHECK:       OPERATOR COLLATE NOCASE
-- CHECK:   ORDER desc
1 COLLATE NOCASE DESC;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR 1.0
-- CHECK:   NULLS first
1 NULLS FIRST;

-- CHECK: ORDERING_TERM_SYNTAX
-- CHECK:   EXPR 1.0
-- CHECK:   NULLS last
1 NULLS LAST;
