-- CHECK: DROP_TABLE_STMT_SYNTAX
-- CHECK:   IF_EXISTS false
-- CHECK:   TABLE_NAME
-- CHECK:     NAME foo
DROP TABLE foo;

-- CHECK: DROP_TABLE_STMT_SYNTAX
-- CHECK:   IF_EXISTS true
-- CHECK:   TABLE_NAME
-- CHECK:     NAME foo
DROP TABLE IF EXISTS foo;

-- CHECK: DROP_TABLE_STMT_SYNTAX
-- CHECK:   IF_EXISTS false
-- CHECK:   TABLE_NAME
-- CHECK:     SCHEMA foo
-- CHECK:     NAME bar
DROP TABLE foo.bar;
