-- CHECK: DROP_VIEW_STMT_SYNTAX
-- CHECK:   IF_EXISTS true
-- CHECK:   SCHEMA_NAME foo
-- CHECK:   VIEW_NAME bar
DROP VIEW IF EXISTS foo.bar;

-- CHECK: DROP_VIEW_STMT_SYNTAX
-- CHECK:   IF_EXISTS false
-- CHECK:   VIEW_NAME bar
DROP VIEW bar;
