-- CHECK: JOIN_CLAUSE_OR_TABLE_OR_SUBQUERIES
-- CHECK:   JOIN
-- CHECK:     TABLE_OR_SUBQUERY
-- CHECK:       KIND
-- CHECK:         TABLE
-- CHECK:           NAME foo
-- CHECK:     JOINS
-- CHECK:       JOIN
-- CHECK:         OP
-- CHECK:           KIND
-- CHECK:             INNER
-- CHECK:               NATURAL false
-- CHECK:         TABLE_OR_SUBQUERY
-- CHECK:           KIND
-- CHECK:             TABLE
-- CHECK:               NAME bar
-- CHECK:         CONSTRAINT
-- CHECK:           KIND none
foo INNER JOIN bar;

-- CHECK: JOIN_CLAUSE_OR_TABLE_OR_SUBQUERIES
-- CHECK:   JOIN
-- CHECK:     TABLE_OR_SUBQUERY
-- CHECK:       KIND
-- CHECK:         TABLE
-- CHECK:           NAME foo
-- CHECK:     JOINS
-- CHECK:       JOIN
-- CHECK:         OP
-- CHECK:           KIND
-- CHECK:             INNER
-- CHECK:               NATURAL false
-- CHECK:         TABLE_OR_SUBQUERY
-- CHECK:           KIND
-- CHECK:             TABLE
-- CHECK:               NAME bar
-- CHECK:         CONSTRAINT
-- CHECK:           KIND none
-- CHECK:       JOIN
-- CHECK:         OP
-- CHECK:           KIND
-- CHECK:             LEFT
-- CHECK:               NATURAL false
-- CHECK:               OUTER false
-- CHECK:         TABLE_OR_SUBQUERY
-- CHECK:           KIND
-- CHECK:             TABLE
-- CHECK:               NAME baz
-- CHECK:         CONSTRAINT
-- CHECK:           KIND none
foo INNER JOIN bar LEFT JOIN baz;

-- CHECK: JOIN_CLAUSE_OR_TABLE_OR_SUBQUERIES
-- CHECK:   JOIN
-- CHECK:     TABLE_OR_SUBQUERY
-- CHECK:       KIND
-- CHECK:         TABLE
-- CHECK:           NAME foo
-- CHECK:     JOINS
-- CHECK:       JOIN
-- CHECK:         OP
-- CHECK:           KIND
-- CHECK:             INNER
-- CHECK:               NATURAL false
-- CHECK:         TABLE_OR_SUBQUERY
-- CHECK:           KIND
-- CHECK:             TABLE
-- CHECK:               NAME bar
-- CHECK:         CONSTRAINT
-- CHECK:           KIND
-- CHECK:             ON 1.0
foo INNER JOIN bar ON 1;

-- CHECK: JOIN_CLAUSE_OR_TABLE_OR_SUBQUERIES
-- CHECK:   JOIN
-- CHECK:     TABLE_OR_SUBQUERY
-- CHECK:       KIND
-- CHECK:         TABLE
-- CHECK:           NAME foo
-- CHECK:     JOINS
-- CHECK:       JOIN
-- CHECK:         OP
-- CHECK:           KIND
-- CHECK:             INNER
-- CHECK:               NATURAL false
-- CHECK:         TABLE_OR_SUBQUERY
-- CHECK:           KIND
-- CHECK:             TABLE_OR_SUBQUERIES
-- CHECK:                 TABLE_OR_SUBQUERY_SYNTAX
-- CHECK:                   KIND
-- CHECK:                     TABLE
-- CHECK:                       NAME bar
-- CHECK:                 TABLE_OR_SUBQUERY_SYNTAX
-- CHECK:                   KIND
-- CHECK:                     TABLE
-- CHECK:                       NAME baz
-- CHECK:         CONSTRAINT
-- CHECK:           KIND none
foo INNER JOIN (bar, baz);
