-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY true
-- CHECK:   IF_NOT_EXISTS true
-- CHECK:   SCHEMA_NAME main
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   MODIFIER after
-- CHECK:   ACTION insert
-- CHECK:   TABLE_SCHEMA_NAME main
-- CHECK:   TABLE_NAME bar
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
CREATE TEMP TRIGGER IF NOT EXISTS
main.foo AFTER INSERT ON main.bar
BEGIN
INSERT INTO foo (id) VALUES (1)
END;

-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY false
-- CHECK:   IF_NOT_EXISTS false
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   ACTION
-- CHECK:     UPDATE
-- CHECK:   TABLE_NAME bar
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
-- CHECK:     UPDATE_STMT_SYNTAX
-- CHECK:       ...
CREATE TRIGGER
foo UPDATE ON bar
BEGIN
INSERT INTO foo (id) VALUES (1);
UPDATE foo SET qux = 1;
END;

-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY false
-- CHECK:   IF_NOT_EXISTS false
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   ACTION
-- CHECK:     UPDATE
-- CHECK:       COLUMNS
-- CHECK:         qux
-- CHECK:   TABLE_NAME bar
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
CREATE TRIGGER
foo UPDATE OF qux ON bar
BEGIN
INSERT INTO foo (id) VALUES (1);
END;

-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY false
-- CHECK:   IF_NOT_EXISTS false
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   ACTION
-- CHECK:     UPDATE
-- CHECK:       COLUMNS
-- CHECK:         qux
-- CHECK:         foo
-- CHECK:   TABLE_NAME bar
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
CREATE TRIGGER
foo UPDATE OF qux, foo ON bar
BEGIN
INSERT INTO foo (id) VALUES (1);
END;

-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY false
-- CHECK:   IF_NOT_EXISTS false
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   MODIFIER insteadOf
-- CHECK:   ACTION delete
-- CHECK:   TABLE_NAME bar
-- CHECK:   WHEN
-- CHECK:     LHS
-- CHECK:       ...
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
CREATE TRIGGER
foo INSTEAD OF DELETE ON bar
FOR EACH ROW WHEN foo > 1
BEGIN
INSERT INTO foo (id) VALUES (1);
END;

-- CHECK: CREATE_TRIGGER_STMT_SYNTAX
-- CHECK:   IS_TEMPORARY false
-- CHECK:   IF_NOT_EXISTS false
-- CHECK:   TRIGGER_NAME foo
-- CHECK:   MODIFIER insteadOf
-- CHECK:   ACTION delete
-- CHECK:   TABLE_NAME bar
-- CHECK:   WHEN
-- CHECK:     LHS
-- CHECK:       ...
-- CHECK:   STATEMENTS
-- CHECK:     INSERT_STMT_SYNTAX
-- CHECK:       ...
CREATE TRIGGER
foo INSTEAD OF DELETE ON bar
WHEN foo > 1
BEGIN
INSERT INTO foo (id) VALUES (1);
END;
