-- CHECK: COLUMN_DEF_SYNTAX
-- CHECK:   NAME age
-- CHECK:   TYPE INT
age INT;

-- CHECK: COLUMN_DEF_SYNTAX
-- CHECK:   NAME age
-- CHECK:   TYPE BIGINT
age BIGINT;

-- CHECK: COLUMN_DEF_SYNTAX
-- CHECK:   NAME age
-- CHECK:   TYPE UNSIGNED BIG INT
-- CHECK:   CONSTRAINTS
-- CHECK:     COLUMN_CONSTRAINT_SYNTAX
-- CHECK:       KIND
-- CHECK:         NOT_NULL none
age UNSIGNED BIG INT NOT NULL
