-- CHECK: COMMON_TABLE_EXPRESSION_SYNTAX
-- CHECK:   TABLE foo
-- CHECK:   COLUMNS
-- CHECK:     id
-- CHECK:     name
-- CHECK:   MATERIALIZED false
-- CHECK:   SELECT
-- CHECK:     SELECTS
-- CHECK:       SINGLE
-- CHECK:         SELECT
-- CHECK:           DISTINCT false
-- CHECK:           COLUMNS
-- CHECK:             RESULT_COLUMN_SYNTAX
-- CHECK:               KIND
-- CHECK:                 ALL
-- CHECK:           FROM
-- CHECK:             JOIN
-- CHECK:               TABLE_OR_SUBQUERY
-- CHECK:                 KIND
-- CHECK:                   TABLE
-- CHECK:                     NAME bar
foo (id, name) AS (SELECT * FROM bar);
