-- CHECK: JOIN_CONSTRAINT_SYNTAX
-- CHECK:   KIND
-- CHECK:     ON 1.0
ON 1;

-- CHECK: JOIN_CONSTRAINT_SYNTAX
-- CHECK:   KIND
-- CHECK:     USING
-- CHECK:       id
USING (id);

-- CHECK: JOIN_CONSTRAINT_SYNTAX
-- CHECK:   KIND
-- CHECK:     USING
-- CHECK:       foo
-- CHECK:       bar
USING (foo, bar);
