-- CHECK: DROP_TRIGGER_STMT_SYNTAX
-- CHECK:   IF_EXISTS true
-- CHECK:   SCHEMA_NAME main
-- CHECK:   TRIGGER_NAME foo
DROP TRIGGER IF EXISTS main.foo;

-- CHECK: DROP_TRIGGER_STMT_SYNTAX
-- CHECK:   IF_EXISTS false
-- CHECK:   TRIGGER_NAME foo
DROP TRIGGER foo;
