-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
REFERENCES user

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
REFERENCES user(id)

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:     foo
REFERENCES user(id, foo)

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON delete
-- CHECK:         DO setNull
REFERENCES user(id) ON DELETE SET NULL

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON delete
-- CHECK:         DO setDefault
REFERENCES user(id) ON DELETE SET DEFAULT

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON delete
-- CHECK:         DO cascade
REFERENCES user ON DELETE CASCADE

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON delete
-- CHECK:         DO restrict
REFERENCES user(id) ON DELETE RESTRICT

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON delete
-- CHECK:         DO noAction
REFERENCES user(id) ON DELETE NO ACTION

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON update
-- CHECK:         DO setNull
REFERENCES user(id) ON UPDATE SET NULL

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON update
-- CHECK:         DO setDefault
REFERENCES user(id) ON UPDATE SET DEFAULT

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON update
-- CHECK:         DO cascade
REFERENCES user ON UPDATE CASCADE

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON update
-- CHECK:         DO restrict
REFERENCES user(id) ON UPDATE RESTRICT

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       ON_DO
-- CHECK:         ON update
-- CHECK:         DO noAction
REFERENCES user(id) ON UPDATE NO ACTION

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       MATCH
-- CHECK:         SIMPLE
-- CHECK:           ACTION
-- CHECK:             ON_DO
-- CHECK:               ON delete
-- CHECK:               DO cascade
-- CHECK:           ACTION
-- CHECK:             ON_DO
-- CHECK:               ON update
-- CHECK:               DO noAction
REFERENCES user(id) MATCH SIMPLE ON DELETE CASCADE ON UPDATE NO ACTION

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       NOT_DEFERRABLE
REFERENCES user(id) NOT DEFERRABLE

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       NOT_DEFERRABLE initiallyDeferred
REFERENCES user(id) NOT DEFERRABLE INITIALLY DEFERRED

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       NOT_DEFERRABLE initiallyImmediate
REFERENCES user(id) NOT DEFERRABLE INITIALLY IMMEDIATE

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       DEFERRABLE
REFERENCES user(id) DEFERRABLE

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       DEFERRABLE initiallyDeferred
REFERENCES user(id) DEFERRABLE INITIALLY DEFERRED

-- CHECK: FOREIGN_KEY_CLAUSE_SYNTAX
-- CHECK:   FOREIGN_TABLE user
-- CHECK:   FOREIGN_COLUMNS
-- CHECK:     id
-- CHECK:   ACTIONS
-- CHECK:     ACTION
-- CHECK:       DEFERRABLE initiallyImmediate
REFERENCES user(id) DEFERRABLE INITIALLY IMMEDIATE
