-- CHECK: SELECT_STMT_SYNTAX
-- CHECK:   CTE_RECURSIVE false
-- CHECK:   SELECTS
-- CHECK:     VALUE
-- CHECK:       SINGLE
-- CHECK:         SELECT
-- CHECK:           DISTINCT false
-- CHECK:           COLUMNS
-- CHECK:             RESULT_COLUMN_SYNTAX
-- CHECK:               KIND
-- CHECK:                 ALL
-- CHECK:           FROM
-- CHECK:             JOIN
-- CHECK:               TABLE_OR_SUBQUERY
-- CHECK:                 KIND
-- CHECK:                   TABLE
-- CHECK:                     NAME foo
SELECT * FROM foo;
