-- CHECK: DROP_INDEX_STMT_SYNTAX
-- CHECK:   IF_EXISTS false
-- CHECK:   NAME foo
DROP INDEX foo;

-- CHECK: DROP_INDEX_STMT_SYNTAX
-- CHECK:   IF_EXISTS true
-- CHECK:   NAME foo
DROP INDEX IF EXISTS foo;
