-- CHECK: DELETE_STMT_SYNTAX
-- CHECK:   TABLE
-- CHECK:     TABLE_NAME
-- CHECK:       NAME user
DELETE FROM user;

-- CHECK: DELETE_STMT_SYNTAX
-- CHECK:   TABLE
-- CHECK:     TABLE_NAME
-- CHECK:       NAME user
-- CHECK:   WHERE_EXPR
-- CHECK:       LHS
-- CHECK:         COLUMN id
-- CHECK:       OPERATOR =
-- CHECK:       RHS ?
DELETE FROM user WHERE id = ?;

-- CHECK: DELETE_STMT_SYNTAX
-- CHECK:   TABLE
-- CHECK:     TABLE_NAME
-- CHECK:       NAME user
-- CHECK:   WHERE_EXPR
-- CHECK:       LHS
-- CHECK:         COLUMN id
-- CHECK:       OPERATOR =
-- CHECK:       RHS ?
-- CHECK:   RETURNING_CLAUSE
-- CHECK:     VALUES
-- CHECK:       VALUE all
DELETE FROM user WHERE id = ? RETURNING *;
