-- CHECK: PRAGMA_STMT_SYNTAX
-- CHECK:   NAME name
-- CHECK:   VALUE
-- CHECK:     LITERAL 1.0
-- CHECK:   IS_FUNCTION_CALL false
PRAGMA name = 1;

-- CHECK: PRAGMA_STMT_SYNTAX
-- CHECK:   NAME name
-- CHECK:   VALUE
-- CHECK:     LITERAL 0.0
-- CHECK:   IS_FUNCTION_CALL true
PRAGMA name(0);

-- CHECK: PRAGMA_STMT_SYNTAX
-- CHECK:   SCHEMA schema
-- CHECK:   NAME name
-- CHECK:   VALUE
-- CHECK:     LITERAL 1.0
-- CHECK:   IS_FUNCTION_CALL true
PRAGMA schema.name(1);
