-- CHECK: RESULT_COLUMN_SYNTAX
-- CHECK:   KIND
-- CHECK:     ALL
*;

-- CHECK: RESULT_COLUMN_SYNTAX
-- CHECK:   KIND
-- CHECK:     ALL
-- CHECK:       TABLE foo
foo.*;

-- CHECK: RESULT_COLUMN_SYNTAX
-- CHECK:   KIND
-- CHECK:     EXPR
-- CHECK:       1.0
1;

-- CHECK: RESULT_COLUMN_SYNTAX
-- CHECK:   KIND
-- CHECK:     EXPR
-- CHECK:       1.0
-- CHECK:       AS one
1 AS one;

-- CHECK: RESULT_COLUMN_SYNTAX
-- CHECK:   KIND
-- CHECK:     EXPR
-- CHECK:       1.0
-- CHECK:       AS one
1 one;
