-- CHECK: REINDEX_STMT_SYNTAX
REINDEX;

-- CHECK: REINDEX_STMT_SYNTAX
-- CHECK:   NAME foo
REINDEX foo;

-- CHECK: REINDEX_STMT_SYNTAX
-- CHECK:   SCHEMA_NAME foo
-- CHECK:   NAME bar
REINDEX foo.bar;
